name: rs
channels:
    - conda-forge
    - defaults
dependencies:
    - geopandas     # Geospatial extension of pandas
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics 
    - pandas        # Labeled data analysis
    - jupyter       # Interactive notebooks
    - shapely       # Vector operations
    - jupyterlab    # Web-based IDE for Project Jupyter
    - rasterio      # Read/write gridded data
    - scikit-learn  # Statistics and machine learning
    - scikit-image  # Image processing
